// Email Notification Service
// Auto-generated by autonomous developer

const nodemailer = require('nodemailer');

class EmailService {
  constructor() {
    this.transporter = nodemailer.createTransport({
      host: process.env.SMTP_HOST || 'smtp.gmail.com',
      port: process.env.SMTP_PORT || 587,
      secure: false,
      auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS
      }
    });
  }

  async sendEmail(to, subject, html) {
    try {
      const info = await this.transporter.sendMail({
        from: process.env.EMAIL_FROM || 'noreply@example.com',
        to,
        subject,
        html
      });

      console.log('Email sent:', info.messageId);
      return { success: true, messageId: info.messageId };
    } catch (error) {
      console.error('Email send failed:', error);
      throw error;
    }
  }

  async sendWelcomeEmail(user) {
    const html = `
      <h1>Welcome to our platform, ${user.username}!</h1>
      <p>Thank you for signing up. We're excited to have you on board.</p>
      <p>Please verify your email by clicking the link below:</p>
      <a href="${process.env.BASE_URL}/verify/${user.verificationToken}">Verify Email</a>
    `;

    return this.sendEmail(user.email, 'Welcome!', html);
  }

  async sendPasswordReset(user, resetToken) {
    const html = `
      <h1>Password Reset Request</h1>
      <p>Click the link below to reset your password:</p>
      <a href="${process.env.BASE_URL}/reset-password/${resetToken}">Reset Password</a>
      <p>This link expires in 1 hour.</p>
    `;

    return this.sendEmail(user.email, 'Password Reset', html);
  }
}

module.exports = EmailService;
