// Landing Page Component
// Auto-generated by autonomous developer

import React from 'react';

const Landing = () => {
  return (
    <div className="landing-page">
      <header className="hero">
        <h1>Welcome to BON</h1>
        <p className="tagline">Your amazing product description goes here</p>
        <button className="cta-button">Get Started</button>
      </header>

      <section className="features">
        <h2>Features</h2>
        <div className="feature-grid">
          <div className="feature">
            <h3>Fast</h3>
            <p>Lightning-fast performance</p>
          </div>
          <div className="feature">
            <h3>Secure</h3>
            <p>Enterprise-grade security</p>
          </div>
          <div className="feature">
            <h3>Scalable</h3>
            <p>Grows with your needs</p>
          </div>
        </div>
      </section>

      <footer>
        <p>&copy; 2026 BON. All rights reserved.</p>
      </footer>
    </div>
  );
};

export default Landing;
