// User Registration System
// Auto-generated by autonomous developer

const bcrypt = require('bcrypt');
const validator = require('validator');

class UserRegistration {
  constructor(database) {
    this.db = database;
    this.saltRounds = 10;
  }

  async register(email, password, username) {
    // Validate input
    if (!validator.isEmail(email)) {
      throw new Error('Invalid email address');
    }

    if (password.length < 8) {
      throw new Error('Password must be at least 8 characters');
    }

    // Check if user exists
    const existingUser = await this.db.findUserByEmail(email);
    if (existingUser) {
      throw new Error('User already exists');
    }

    // Hash password
    const hashedPassword = await bcrypt.hash(password, this.saltRounds);

    // Create user
    const user = await this.db.createUser({
      email,
      username,
      password: hashedPassword,
      createdAt: new Date(),
      verified: false
    });

    return {
      id: user.id,
      email: user.email,
      username: user.username
    };
  }

  async sendVerificationEmail(userId) {
    // TODO: Implement email verification
    console.log(`Sending verification email to user ${userId}`);
  }
}

module.exports = UserRegistration;
